name: Abhishek CI workflows

on:
  push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
            - uses: actions/checkout@v4 #clone codes into ubuntu runner
            
            - name: Setup code
            - uses: docker/setup-buildx-action@v4

