name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:

    Gitleaks:
        name: Git Secrets Scan
        uses: ./.github/workflows/gitleaks.yml
        

    SonarQube:
        needs: Gitleaks
        name: Secuirty_Checks 
        uses: ./.github/workflows/sonarqube.yml

    Linting:
        needs: SonarQube
        name: Check_Code_linting
        uses: ./.github/workflows/linting.yml
    

    Build_and_Push:
        
        name: Docker Build and Push
        uses: ./.github/workflows/Docker_build_push.yml
        secrets: inherit
        
    Trivy_image_Scan:
        needs: Build_and_Push
        name: Docker Image Scan
        uses: ./.github/workflows/trivy.yml
        secrets: inherit